# Generated by Django 3.1.5 on 2021-02-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_model_manager_app', '0003_auto_20210201_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeltraindata',
            old_name='data_name',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='modeltraindata',
            old_name='model_name',
            new_name='model',
        ),
    ]
