# Generated by Django 3.1.5 on 2021-02-01 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_model_manager_app', '0004_auto_20210201_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeltraindata',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
