# Generated by Django 3.1.5 on 2021-02-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_model_manager_app', '0005_modeltraindata_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
    ]
