# Generated by Django 3.1.5 on 2021-02-03 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_model_manager_app', '0009_auto_20210202_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='iqa_0',
            new_name='brightness',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='iqa_1',
            new_name='brisque',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='iqa_2',
            new_name='mean_height',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='shape_0',
            new_name='mean_width',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='shape_1',
            new_name='sharpness',
        ),
    ]
