# Generated by Django 3.1.5 on 2021-02-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_model_manager_app', '0010_auto_20210203_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
