# Generated by Django 3.1.5 on 2021-02-08 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_model_manager_app', '0012_auto_20210205_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Dataset',
        ),
    ]
